name: clover
description: A new Flutter project.
publish_to: 'none'
version: 0.0.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl_phone_field: ^3.2.0
  appwrite: ^11.0.1
  hexcolor: ^3.0.1
  font_awesome_flutter: ^10.6.0
  provider: ^6.1.1
  loading_animation_widget: ^1.2.0+4
  flutter_pin_code_fields: ^2.2.0
  flutter_bloc: ^8.1.3
  shimmer: ^3.0.0
  intl: ^0.19.0
  dotted_border: ^2.1.0
  liquid_pull_to_refresh: ^3.0.1

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Light.ttf
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin-Regular.ttf
        - asset: assets/fonts/Cabin-Bold.ttf

